# Generated by Django 4.0.3 on 2022-05-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_number_easy', models.IntegerField(default=0)),
                ('games_number_medium', models.IntegerField(default=0)),
                ('games_number_hard', models.IntegerField(default=0)),
                ('best_time_easy', models.DurationField(default=0)),
                ('best_time_medium', models.DurationField(default=0)),
                ('best_time_hard', models.DurationField(default=0)),
                ('puzzle_created_number_easy', models.IntegerField(default=0)),
                ('puzzle_created_number_medium', models.IntegerField(default=0)),
                ('puzzle_created_number_hard', models.IntegerField(default=0)),
            ],
        ),
    ]
