# Generated by Django 4.0.3 on 2022-05-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudoku',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
