# Generated by Django 4.0.3 on 2022-05-30 20:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0003_sudoku_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudoku',
            name='puzzle',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), max_length=9, size=None), max_length=9, size=None),
        ),
    ]
