# Generated by Django 4.0.3 on 2022-05-30 20:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0004_alter_sudoku_puzzle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudoku',
            name='puzzle',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1), max_length=9, size=None), max_length=9, size=None),
        ),
    ]
